meta:
  version: 2
  flow: Classic
  substituting_steps:
    KLayout.DRC: null
    Checker.KLayoutDRC: null

# DO CHANGE
DESIGN_NAME: sid
VERILOG_FILES: ["dir::src/SID_channels.v", "dir::src/SID_filter.v", "dir::src/SID_top.v", "dir::src/spi_dac_i.v", "dir::src/tt_um_rejunity_sn76489.v"]
CLOCK_PERIOD: 35
DIE_AREA: [0, 0, 750, 775]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: DELAY 4
PL_RESIZER_SETUP_SLACK_MARGIN: 0.1
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.1
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.6
PL_RESIZER_HOLD_SLACK_MARGIN: 0.6
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100
RT_MAX_LAYER: Metal4
PNR_SDC_FILE: dir::../base.sdc
SIGNOFF_SDC_FILE: dir::../base.sdc
RUN_CTS: true
MAX_FANOUT_CONSTRAINT: 5
CLOCK_PORT: clk
CLOCK_NET: clk
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
