meta:
  version: 2
  flow: Classic
  substituting_steps:
    KLayout.DRC: null
    Checker.KLayoutDRC: null

# DO CHANGE
DESIGN_NAME: timers
VERILOG_FILES: "dir::src/timers.v"
CLOCK_PERIOD: 25
DIE_AREA: [0, 0, 425, 425]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: DELAY 4
PL_RESIZER_SETUP_SLACK_MARGIN: 0.15
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.15
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.25
PL_RESIZER_HOLD_SLACK_MARGIN: 0.25
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100

# DO NOT CHANGE
RUN_CTS: true
MAX_FANOUT_CONSTRAINT: 4
MAX_TRANSITION_CONSTRAINT: 1.5
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
