meta:
  version: 2
  flow: Classic
  substituting_steps:
    KLayout.DRC: null
    Checker.KLayoutDRC: null

# DO CHANGE
DESIGN_NAME: ram_controller
VERILOG_FILES: "dir::src/ram_controller.v"
CLOCK_PERIOD: 18
DIE_AREA: [0, 0, 550, 250]
RUN_MAGIC_DRC: true
PL_RESIZER_SETUP_SLACK_MARGIN: 0.2
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.2
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.2
PL_RESIZER_HOLD_SLACK_MARGIN: 0.2
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100
SYNTH_STRATEGY: DELAY 4
PNR_SDC_FILE: dir::../base.sdc
SIGNOFF_SDC_FILE: dir::../base.sdc
RUN_CTS: true
MAX_FANOUT_CONSTRAINT: 4
MAX_TRANSITION_CONSTRAINT: 1.5
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
