meta:
  version: 2
  flow: Classic
  substituting_steps:
    KLayout.DRC: null
    Checker.KLayoutDRC: null

# DO CHANGE
DESIGN_NAME: boot_rom
VERILOG_FILES: "dir::src/boot_rom.v"
CLOCK_PERIOD: 20
DIE_AREA: [0, 0, 210, 210]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: DELAY 0
PL_RESIZER_SETUP_SLACK_MARGIN: 0.1
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.1
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.25
PL_RESIZER_HOLD_SLACK_MARGIN: 0.25
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100
PNR_SDC_FILE: dir::../base.sdc
SIGNOFF_SDC_FILE: dir::../base.sdc
RUN_CTS: true
MAX_FANOUT_CONSTRAINT: 4
MAX_TRANSITION_CONSTRAINT: 1.5
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
